### ISSUE TITLE
Error while running example code in documentation

### ISSUE THREAD

**Issue by kdmccormick** [matthiask/django-content-editor#4]
I made a new Django application and added the example code from the documentation. When I try to run my server, I get the following error:
```
Unhandled exception in thread started by <function wrapper at 0x24dee60>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line
n inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 252, in raise_last
tion
    six.reraise(*_exception)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/__init__.py", line 24, in autod
r
    autodiscover_modules('admin', register_to=site)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py", line 74, in autodis
modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/vagrant/app/TestSite/admin.py", line 39, in <module>
    ContentEditorInline.create(model=Download),
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 105, in registe
    system_check_errors.extend(admin_class.check(model))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 150, in check
    return cls.checks_class().check(cls, model, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/checks.py", line 498, in check
    errors.extend(self._check_inlines(cls, model))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/checks.py", line 536, in _check
es
    for index, item in enumerate(cls.inlines)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/checks.py", line 567, in _check
es_item
    return inline.check(model)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 150, in check
    return cls.checks_class().check(cls, model, **kwargs)
TypeError: check() takes exactly 2 arguments (3 given)
```
I am using Django 1.8.7, Python 2.7.3, and the latest version of djangocms-content-editor.

**Comment by matthiask** [comment]
Thank you for the report! It seems that the API for checks changed between 1.8 and 1.9. By the way, Django 1.8 isn't properly supported because it lacks the support for the `formset:added` and `formset:removed` signals in the admin inlines JavaScript code (resp. the inlines code does not emit those events, and they are required, for example for attaching a rich text widget to an inlines' textarea)

Is it possible for you to upgrade your project to Django 1.9?
